version: 2.1

defaults: &defaults
  docker:
    - image: circleci/clojure:tools-deps-1.10.1.619-node

orbs:
  clojure: lambdaisland/clojure@0.0.1
  node: circleci/node@4.0.0

jobs:
  test-clj:
    <<: *defaults

    steps:
      - checkout

      - clojure/with_cache:
          steps:
            - run:
                name: Clojure tests
                command: clojure -A:test:test-runner --reporter kaocha.report/documentation --plugin profiling

  test-cljs:
    <<: *defaults

    steps:
      - checkout

      - node/install-packages
      - clojure/with_cache:
          steps:
            - run:
                name: ClojureScript tests
                command: ./bin/run-cljs-tests.sh



workflows:
  version: 2
  ci-workflow:
    jobs:
      - test-clj
      - test-cljs