version: 2.1

defaults: &defaults
  docker:
    - image: circleci/clojure:tools-deps-1.10.1.502

jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - project-{{ checksum "deps.edn" }}
            - project

      - run: clojure -A:test:test-runner --reporter kaocha.report/documentation --plugin profiling

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
            - ./.cpcache
          key: project-{{ checksum "deps.edn" }}


workflows:
  version: 2
  ci-workflow:
    jobs:
      - test