version: 2.1

defaults: &defaults
  docker:
    - image: circleci/clojure:tools-deps-1.10.1.502-node

jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - project-{{ checksum "deps.edn" }}
            - project

      - run:
          name: Clojure tests
          command: clojure -A:test:test-runner --reporter kaocha.report/documentation --plugin profiling
      - run:
          # TODO: Replace with Kaocha
          # Tried using Kaocha but it always fails with: clojure.lang.ExceptionInfo: Kaocha ClojureScript client failed connecting back.
          name: ClojureScript tests
          command: |
            npm install
            ./bin/run-cljs-tests.sh

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
            - ./.cpcache
          key: project-{{ checksum "deps.edn" }}


workflows:
  version: 2
  ci-workflow:
    jobs:
      - test